AplicacionesGane/project_cartera_company

client/package.json, client/src/components/NavBar.tsx, client/src/components/TableDatos.tsx, client/src/components/TableInfo.tsx, client/src/components/ui/Button.tsx, client/src/components/ui/UserInfo.tsx, client/src/index.css, client/src/pages/BasesDetalle.tsx, client/src/pages/BasesPage.tsx, client/src/pages/Home.tsx, client/src/pages/Login.tsx
se realizan cambios minimos de estilos colores y algun detalle a nivel visual
=> Cambio de estilos y bg

api/package.json, api/src/connections/index.ts, api/src/controllers/recaudo.controller.ts, api/src/model/recaudo.model.ts, api/src/routes/recaudo.routes.ts
se agrega ruta en la api cartera para solicitar la info y generar el reporte en el front end
=> Ruta Agregada en la api cartera 

api/src/controllers/recaudo.controller.ts, api/src/model/recaudo.model.ts, api/src/model/sellers.model.ts
Se realiza cambios a controllador de la info para el reporte.
Adecuandola a los parametros solicitados por el solicitante.
=> Modificación para la solicitud Reporte

client/src/components/ExportReporteRecaudo.tsx, client/src/pages/ReporteRecaudo.tsx, client/src/types/Recaudo.d.ts
agregando los types para el reporte cartera y agregando el componente de exportación en archivo excel
=> Cambios realizados

api/src/controllers/recaudo.controller.ts, client/src/components/ExportReporteRecaudo.tsx, client/src/pages/ReporteRecaudo.tsx, client/src/types/Recaudo.d.ts
Se realizan ajustes y cambios necesarios para terminar de implementar la generación de resporte de transportes recaudos.
anexo images.
=> Cambios Finales para reporte Trasnportes

api/src/services/cartera.services.ts
fix error types seller.
se organiza error el cual no correspondía a las keys de la classe seller, la cual hace referencia a la table VENDEDORES
=> Fix type reference for seller attributes in cartera services

api/src/connections/index.ts, client/src/pages/ReporteRecaudo.tsx
se agrega filtro x documento en el reporteador de transportes recaudos
=> agregando filtro para la lista de reportes

client/src/pages/ReporteRecaudo.tsx, client/src/types/Recaudo.d.ts
agregando fecha a reporte visual
=> Add 'Fecha' column to ReporteRecaudo and update DataReporte type

api/src/controllers/recaudo.controller.ts, api/src/types/interface.d.ts
se ha cambiado la forma de retornar al front la data
=> mapeando los results para ser ameno el front end

client/src/pages/ReportOracle.tsx, client/src/types/Recaudo.d.ts
arreglo de la page reporOracle
=> arreglo de reporOracle

api/src/controllers/recaudo.controller.ts, api/src/routes/recaudo.routes.ts, api/src/services/report.services.ts
Se han realizado los cambios necesarios para que la presente consulta, sea dinamíca. la cual en el front ahora se debera cambiar a petición POST y recibirá dos parámetros documento a consultar y la fecha a consultar
=> ultimos cambios para consulta dinámica

api/src/controllers/recaudo.controller.ts, api/src/services/report.services.ts, client/src/pages/ReportOracle.tsx
se han realizado ultimos cambios a nivel de front y backend para hacer la consulta dinámica
=> ultimos cambios para hacer consulta dinámica

.gitignore, Jenkinsfile, api/Dockerfile, api/src/connections/oracledb.ts
se cambiado todos los pasos necesarios para hacer funcionar oracle db en el contenedor de la API
=> Agregando despliegue automatico

Jenkinsfile
=> modificando jenkisn file

client/package.json, client/src/components/ReporteDetail.tsx, client/src/components/ui/DialogTremor.tsx, client/src/pages/ReporteRecaudo.tsx
se realizo una forma para ver mas detallado los recaudos obre el exportador
=> detalle sobre el exportador de recaudos

api/package.json, api/src/controllers/recaudo.controller.ts, api/src/services/report.services.ts, client/src/components/InfoPersonReport.tsx, client/src/pages/ReportOracle.tsx, client/src/routes/root.tsx
- Se realiza modificación para realizar consulta de ventas x rango de fecha
- Se establece limite de 62 días como consulta máxima
=> cambios aplicados a report oracle

api/src/controllers/recaudo.controller.ts, client/src/components/ExportReporteRecaudo.tsx, client/src/pages/ReporteRecaudo.tsx, client/src/types/Recaudo.d.ts
- Se realiza cambio en la api para enviar en la generación del reporte el nombre cargo de la persona
- Se cambia types and vista de reporte recaudo en el Front End
- Se Cambia información que exportará la generación del excel agregando el nombre cargo seguido del nombre colocador
=> Cambios reporte recaudo

Jenkinsfile, client/pnpm-lock.yaml
- se agrega archivo pnpm para despliegue
=> cambiando jenkins file

api/.env.example, api/src/config/index.ts, api/src/connections/mngr.ts, api/src/connections/oracledb.ts, api/src/index.ts, api/src/services/report.services.ts
revisar los commits para mayor detalle del orden de los cambios realizados
=> cambiand las env y validando datos de entrada

api/src/controllers/cartera.controller.ts, api/src/controllers/recaudo.controller.ts, api/src/routes/cartera.routes.ts, api/src/services/report.services.ts
=> Implementando nuevas querys

api/src/controllers/cartera.controller.ts, api/src/model/cartera.model.ts, client/src/pages/ReportMngr.tsx
- se ha realizado la primera implementación para las diferentes empresas
=> implementación de empresas
